### ISSUE TITLE
porting new device

### ISSUE THREAD

**Issue by weiay** [ViperOS-Project/viper_manifest#1]
can you build this.ROM.for xiaomi note(Virgo) ?

**Comment by willem640** [comment]
You can do some porting yourself....
If you have the sources for the device (kernel,device)
You're good to go, copy them in the right path after copying the repo, if you have cloned it place the file in devices/xiaomi/virgo, and the kernel in kernel/xiaomi/virgo
You also have to create viper.mk and viper.dependencies, they are not hard to learn, just have a look at the existing ones for xiaomi

This might go terribly wrong so I suggest you make a backup before flashing. If you get any errors just Google them.

I have described the very basic porting process. After following these steps, you can find your device in breakfast/brunch/lunch following the normal building guide.

Do not follow this guide unless you are familiar with building and porting AOSP or based ROMs.

This is how it should work but viper may be very different from other ROMs so this might not work
